import path from "node:path";
import { randomUUID } from "node:crypto";
import { copyFile, readFile, readdir, realpath, rm, stat } from "node:fs/promises";
import { BuilderError } from "./errors.js";
import { ensureDir, exists, sha256File, writeJson } from "./fs-utils.js";

export type SampleStatus = "draft" | "pending" | "publish" | "private" | "future";
export type SampleTaxonomy = "category" | "post_tag" | "product_cat" | "product_tag" | "product_brand" | "product_shipping_class" | `pa_${string}`;
export interface SampleTerm { id: string; taxonomy: SampleTaxonomy; name: string; slug: string; description: string; parentId?: string; imageId?: string; }
export interface SampleGlobalAttribute { id: string; name: string; slug: string; type: "select"; orderBy: "menu_order" | "name" | "name_num" | "id"; hasArchives: boolean; }
export interface SampleAsset { id: string; filename: string; file: string; mime: string; size: number; sha256: string; kind: "image" | "download"; alt: string; caption: string; description: string; }
export interface SampleDownload { id: string; name: string; assetId: string; }
export interface SamplePricing { regularPrice: string; salePrice: string; saleFrom?: string; saleTo?: string; }
export interface SampleInventory { sku: string; globalUniqueId: string; manageStock: boolean; quantity: number | null; stockStatus: "instock" | "outofstock" | "onbackorder"; backorders: "no" | "notify" | "yes"; lowStockThreshold: number | null; soldIndividually: boolean; }
export interface SampleShipping { weight: string; length: string; width: string; height: string; classId?: string; }
export interface SampleAttribute { id: string; globalId?: string; name: string; options: string[]; visible: boolean; variation: boolean; }
export interface SampleVariation { id: string; attributes: Record<string, string>; enabled: boolean; description: string; imageId?: string; pricing: SamplePricing; inventory: SampleInventory; shipping: SampleShipping; taxClass: string; virtual: boolean; downloadable: boolean; downloads: SampleDownload[]; downloadLimit: number | null; downloadExpiry: number | null; }
interface SampleBase { id: string; kind: "post" | "product"; title: string; slug: string; content: string; status: SampleStatus; publishAt?: string; categoryIds: string[]; tagIds: string[]; featuredImageId?: string; createdAt: string; updatedAt: string; }
export interface SamplePost extends SampleBase { kind: "post"; excerpt: string; commentStatus: "open" | "closed"; pingStatus: "open" | "closed"; sticky: boolean; format: "standard" | "aside" | "gallery" | "link" | "image" | "quote" | "status" | "video" | "audio" | "chat"; }
interface SampleProductBase extends SampleBase { kind: "product"; shortDescription: string; brandIds: string[]; galleryIds: string[]; catalogVisibility: "visible" | "catalog" | "search" | "hidden"; featured: boolean; inventory: SampleInventory; shipping: SampleShipping; taxStatus: "taxable" | "shipping" | "none"; taxClass: string; upsellIds: string[]; crossSellIds: string[]; attributes: SampleAttribute[]; purchaseNote: string; menuOrder: number; reviewsAllowed: boolean; }
export interface SampleSimpleProduct extends SampleProductBase { productType: "simple"; pricing: SamplePricing; virtual: boolean; downloadable: boolean; downloads: SampleDownload[]; downloadLimit: number | null; downloadExpiry: number | null; }
export interface SampleVariableProduct extends SampleProductBase { productType: "variable"; variations: SampleVariation[]; defaultAttributes: Record<string, string>; }
export interface SampleGroupedProduct extends SampleProductBase { productType: "grouped"; childrenIds: string[]; }
export interface SampleExternalProduct extends SampleProductBase { productType: "external"; pricing: SamplePricing; externalUrl: string; buttonText: string; }
export type SampleProduct = SampleSimpleProduct | SampleVariableProduct | SampleGroupedProduct | SampleExternalProduct;
export type SampleContent = SamplePost | SampleProduct;
export interface SampleContentLibrary { schemaVersion: 1; content: SampleContent[]; terms: SampleTerm[]; attributes: SampleGlobalAttribute[]; assets: SampleAsset[]; }
export interface ResolvedSampleContent extends SampleContentLibrary { selectedIds: string[]; assets: Array<SampleAsset & { absoluteFile: string }>; }
export interface SampleContentPayload extends SampleContentLibrary { selectedIds: string[]; }
export interface SampleValidationIssue { field: string; message: string; }
export class SampleContentValidationError extends BuilderError {
  readonly issues: SampleValidationIssue[];
  constructor(issues: SampleValidationIssue[]) { super("invalid_sample_content", issues.map(i => `${i.field}: ${i.message}`).join("; ")); this.issues = issues; }
}
const emptyLibrary = (): SampleContentLibrary => ({ schemaVersion: 1, content: [], terms: [], attributes: [], assets: [] });
const id = (prefix: string) => `${prefix}-${randomUUID()}`;
const object = (v: unknown): Record<string, any> => v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, any> : {};
const allowedId = /^[a-z][a-z0-9-]{0,79}$/;
const MAX_IMAGE = 20 * 1024 ** 2, MAX_DOWNLOAD = 50 * 1024 ** 2;
export const SAMPLE_BUILD_ASSET_LIMIT = 500 * 1024 ** 2;
export function sampleSlug(value: string): string { return value.normalize("NFKC").trim().toLowerCase().replace(/[^\p{L}\p{N}\p{M}_-]+/gu, "-").replace(/-+/g, "-").replace(/^-|-$/g, ""); }
class Validator {
  issues: SampleValidationIssue[] = [];
  fail(field: string, message: string): void { this.issues.push({ field, message }); }
  text(value: unknown, field: string, fallback = "", max = 1000000): string { if (value === undefined) return fallback; if (typeof value !== "string") { this.fail(field, "Must be text."); return fallback; } if (value.length > max || value.includes("\0")) this.fail(field, `Must not contain NUL and must be at most ${max} characters.`); return value; }
  bool(value: unknown, field: string, fallback = false): boolean { if (value === undefined) return fallback; if (typeof value !== "boolean") { this.fail(field, "Must be a boolean."); return fallback; } return value; }
  choice<T extends string>(value: unknown, field: string, values: readonly T[], fallback: T): T { if (value === undefined) return fallback; if (!values.includes(value as T)) { this.fail(field, `Choose ${values.join(", ")}.`); return fallback; } return value as T; }
  integer(value: unknown, field: string, fallback: number | null = null, minimum = 0): number | null { if (value === undefined || value === null) return fallback; if (typeof value !== "number" || !Number.isSafeInteger(value) || value < minimum) { this.fail(field, `Must be an integer of at least ${minimum}, or empty.`); return fallback; } return value; }
  list(value: unknown, field: string): unknown[] { if (value === undefined) return []; if (!Array.isArray(value)) { this.fail(field, "Must be an array."); return []; } if (value.length > 10000) { this.fail(field, "Too many entries."); return []; } return value; }
  identifier(value: unknown, field: string, fallback?: string): string { const s = this.text(value, field, fallback || "", 80); if (!allowedId.test(s)) this.fail(field, "Invalid logical ID."); return s; }
  optionalId(value: unknown, field: string): string | undefined { if (value === undefined || value === "") return undefined; return this.identifier(value, field); }
  ids(value: unknown, field: string): string[] { const list = this.list(value, field).map((v, i) => this.identifier(v, `${field}[${i}]`)); if (new Set(list).size !== list.length) this.fail(field, "Duplicate references are not allowed."); return list; }
  name(value: unknown, field: string): string { const s = this.text(value, field, "", 200).trim(); if (!s) this.fail(field, "Required."); return s; }
  slug(value: unknown, field: string, name: string, attribute = false): string { const s = this.text(value, field, "", 200).trim() || sampleSlug(name); if (!s || sampleSlug(s) !== s) this.fail(field, "Use a lowercase slug with letters, numbers, underscores or hyphens."); if (attribute && (!/^[a-z][a-z0-9_-]{0,27}$/.test(s) || s.startsWith("pa_"))) this.fail(field, "Global attribute slug must be ASCII, at most 28 characters, without the pa_ prefix."); return s; }
  decimal(value: unknown, field: string): string { const s = this.text(value, field, "", 40); if (s && !/^(?:0|[1-9]\d*)(?:\.\d+)?$/.test(s)) this.fail(field, "Use a non-negative decimal string, or leave empty."); return s; }
  date(value: unknown, field: string): string | undefined { if (value === undefined || value === "") return undefined; const s = this.text(value, field, "", 40); if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?(?:Z|[+-]\d{2}:\d{2})$/.test(s) || !Number.isFinite(Date.parse(s))) this.fail(field, "Use an ISO date with timezone offset."); return s; }
  finish(): void { if (this.issues.length) throw new SampleContentValidationError(this.issues); }
}
function decimalCompare(a: string, b: string): number { const [ai, af = ""] = a.split("."), [bi, bf = ""] = b.split("."); if (ai.length !== bi.length) return ai.length - bi.length; return ai.localeCompare(bi) || af.padEnd(Math.max(af.length, bf.length), "0").localeCompare(bf.padEnd(Math.max(af.length, bf.length), "0")); }
function pricing(raw: unknown, v: Validator, p: string): SamplePricing { const r = object(raw), regularPrice = v.decimal(r.regularPrice, `${p}.regularPrice`), salePrice = v.decimal(r.salePrice, `${p}.salePrice`), saleFrom = v.date(r.saleFrom, `${p}.saleFrom`), saleTo = v.date(r.saleTo, `${p}.saleTo`); if (salePrice && (!regularPrice || decimalCompare(salePrice, regularPrice) >= 0)) v.fail(`${p}.salePrice`, "A sale price must be below the regular price."); if ((saleFrom || saleTo) && !salePrice) v.fail(p, "Sale dates require a sale price."); if (saleFrom && saleTo && Date.parse(saleFrom) > Date.parse(saleTo)) v.fail(p, "Sale end must not precede start."); return { regularPrice, salePrice, saleFrom, saleTo }; }
function inventory(raw: unknown, v: Validator, p: string): SampleInventory { const r = object(raw); const result: SampleInventory = { sku: v.text(r.sku, `${p}.sku`, "", 100).trim(), globalUniqueId: v.text(r.globalUniqueId, `${p}.globalUniqueId`, "", 100).trim(), manageStock: v.bool(r.manageStock, `${p}.manageStock`), quantity: v.integer(r.quantity, `${p}.quantity`, null, -999999999), stockStatus: v.choice(r.stockStatus, `${p}.stockStatus`, ["instock", "outofstock", "onbackorder"], "instock"), backorders: v.choice(r.backorders, `${p}.backorders`, ["no", "notify", "yes"], "no"), lowStockThreshold: v.integer(r.lowStockThreshold, `${p}.lowStockThreshold`), soldIndividually: v.bool(r.soldIndividually, `${p}.soldIndividually`) }; if (result.manageStock && result.quantity === null) v.fail(`${p}.quantity`, "Quantity is required when managing stock."); if (!result.manageStock && (result.quantity !== null || result.lowStockThreshold !== null || result.backorders !== "no")) v.fail(p, "Quantity, low-stock threshold and backorders require stock management."); return result; }
function shipping(raw: unknown, v: Validator, p: string): SampleShipping { const r = object(raw); return { weight: v.decimal(r.weight, `${p}.weight`), length: v.decimal(r.length, `${p}.length`), width: v.decimal(r.width, `${p}.width`), height: v.decimal(r.height, `${p}.height`), classId: v.optionalId(r.classId, `${p}.classId`) }; }
function downloads(r: Record<string, any>, v: Validator, p: string): Pick<SampleSimpleProduct, "virtual" | "downloadable" | "downloads" | "downloadLimit" | "downloadExpiry"> { const rows = v.list(r.downloads, `${p}.downloads`).map((row, i) => { const d = object(row), f = `${p}.downloads[${i}]`; return { id: v.identifier(d.id, `${f}.id`, id("download")), name: v.name(d.name, `${f}.name`), assetId: v.identifier(d.assetId, `${f}.assetId`) }; }); const downloadable = v.bool(r.downloadable, `${p}.downloadable`); if (!downloadable && rows.length) v.fail(`${p}.downloads`, "Enable downloadable to attach files."); if (downloadable && !rows.length) v.fail(`${p}.downloads`, "Add at least one file for a downloadable product."); return { virtual: v.bool(r.virtual, `${p}.virtual`), downloadable, downloads: rows, downloadLimit: v.integer(r.downloadLimit, `${p}.downloadLimit`), downloadExpiry: v.integer(r.downloadExpiry, `${p}.downloadExpiry`) }; }
function mapping(raw: unknown, v: Validator, p: string): Record<string, string> { if (raw === undefined) return {}; if (!raw || typeof raw !== "object" || Array.isArray(raw)) { v.fail(p, "Must be an attribute/value map."); return {}; } const result: Record<string, string> = {}; for (const [key, val] of Object.entries(raw)) { v.identifier(key, `${p}.${key}`); if (["__proto__", "constructor", "prototype"].includes(key)) { v.fail(p, "Reserved key."); continue; } result[key] = v.text(val, `${p}.${key}`, "", 200); } return result; }
export function normalizeSampleContent(input: unknown, existing?: SampleContent): SampleContent {
  const v = new Validator(), r = object(input), kind = v.choice(r.kind, "kind", ["post", "product"], "post"), title = v.name(r.title, "title"), now = new Date().toISOString();
  if (existing && kind !== existing.kind) v.fail("kind", "Content kind cannot be changed.");
  const base = { id: existing?.id || v.identifier(r.id, "id", id(kind)), kind, title, slug: v.slug(r.slug, "slug", title), content: v.text(r.content, "content"), status: v.choice(r.status, "status", ["draft", "pending", "publish", "private", "future"], "draft"), publishAt: v.date(r.publishAt, "publishAt"), categoryIds: v.ids(r.categoryIds, "categoryIds"), tagIds: v.ids(r.tagIds, "tagIds"), featuredImageId: v.optionalId(r.featuredImageId, "featuredImageId"), createdAt: existing?.createdAt || now, updatedAt: now };
  if (base.status === "future" && !base.publishAt) v.fail("publishAt", "Scheduled content requires a date.");
  if (base.status === "future" && base.publishAt && Date.parse(base.publishAt) <= Date.now()) v.fail("publishAt", "Scheduled date must be in the future.");
  let result: SampleContent;
  if (kind === "post") result = { ...base, kind, excerpt: v.text(r.excerpt, "excerpt"), commentStatus: v.choice(r.commentStatus, "commentStatus", ["open", "closed"], "closed"), pingStatus: v.choice(r.pingStatus, "pingStatus", ["open", "closed"], "closed"), sticky: v.bool(r.sticky, "sticky"), format: v.choice(r.format, "format", ["standard", "aside", "gallery", "link", "image", "quote", "status", "video", "audio", "chat"], "standard") };
  else {
    const common: SampleProductBase = { ...base, kind, shortDescription: v.text(r.shortDescription, "shortDescription"), brandIds: v.ids(r.brandIds, "brandIds"), galleryIds: v.ids(r.galleryIds, "galleryIds"), catalogVisibility: v.choice(r.catalogVisibility, "catalogVisibility", ["visible", "catalog", "search", "hidden"], "visible"), featured: v.bool(r.featured, "featured"), inventory: inventory(r.inventory, v, "inventory"), shipping: shipping(r.shipping, v, "shipping"), taxStatus: v.choice(r.taxStatus, "taxStatus", ["taxable", "shipping", "none"], "taxable"), taxClass: v.text(r.taxClass, "taxClass", "", 100), upsellIds: v.ids(r.upsellIds, "upsellIds"), crossSellIds: v.ids(r.crossSellIds, "crossSellIds"), attributes: v.list(r.attributes, "attributes").map((raw, i) => { const a = object(raw), f = `attributes[${i}]`; return { id: v.identifier(a.id, `${f}.id`, id("attribute")), globalId: v.optionalId(a.globalId, `${f}.globalId`), name: v.name(a.name, `${f}.name`), options: v.list(a.options, `${f}.options`).map((o, j) => v.name(o, `${f}.options[${j}]`)), visible: v.bool(a.visible, `${f}.visible`, true), variation: v.bool(a.variation, `${f}.variation`) }; }), purchaseNote: v.text(r.purchaseNote, "purchaseNote"), menuOrder: v.integer(r.menuOrder, "menuOrder", 0, -999999999) || 0, reviewsAllowed: v.bool(r.reviewsAllowed, "reviewsAllowed", true) };
    const productType = v.choice(r.productType, "productType", ["simple", "variable", "grouped", "external"], "simple");
    if (productType === "simple") result = { ...common, productType, pricing: pricing(r.pricing, v, "pricing"), ...downloads(r, v, "product") };
    else if (productType === "external") { const externalUrl = v.text(r.externalUrl, "externalUrl", "", 2048); if (externalUrl) { try { const url = new URL(externalUrl); if (!["http:", "https:"].includes(url.protocol) || url.username || url.password) throw new Error(); } catch { v.fail("externalUrl", "Use an HTTP(S) URL without credentials."); } } if (base.status !== "draft" && !externalUrl) v.fail("externalUrl", "External products require a URL before publication."); result = { ...common, productType, pricing: pricing(r.pricing, v, "pricing"), externalUrl, buttonText: v.text(r.buttonText, "buttonText", "", 200) }; }
    else if (productType === "grouped") result = { ...common, productType, childrenIds: v.ids(r.childrenIds, "childrenIds") };
    else { const variations = v.list(r.variations, "variations").map((raw, i): SampleVariation => { const a = object(raw), f = `variations[${i}]`; return { id: v.identifier(a.id, `${f}.id`, id("variation")), attributes: mapping(a.attributes, v, `${f}.attributes`), enabled: v.bool(a.enabled, `${f}.enabled`, true), description: v.text(a.description, `${f}.description`), imageId: v.optionalId(a.imageId, `${f}.imageId`), pricing: pricing(a.pricing, v, `${f}.pricing`), inventory: inventory(a.inventory, v, `${f}.inventory`), shipping: shipping(a.shipping, v, `${f}.shipping`), taxClass: v.text(a.taxClass, `${f}.taxClass`, "parent", 100), ...downloads(a, v, f) }; }); if (variations.length > 200) v.fail("variations", "At most 200 variations are allowed."); result = { ...common, productType, variations, defaultAttributes: mapping(r.defaultAttributes, v, "defaultAttributes") }; }
    if (new Set(common.attributes.map(a => a.id)).size !== common.attributes.length) v.fail("attributes", "Attribute IDs must be unique.");
    if (new Set(common.attributes.map(a => a.globalId || sampleSlug(a.name))).size !== common.attributes.length) v.fail("attributes", "Attribute names/global selections must be unique.");
    for (const [i, a] of common.attributes.entries()) { if (new Set(a.options).size !== a.options.length) v.fail(`attributes[${i}].options`, "Duplicate options."); if (productType !== "variable" && a.variation) v.fail(`attributes[${i}].variation`, "Variation attributes require a variable product."); }
    if (result.productType === "variable") {
      const attrs = new Map(result.attributes.filter(a => a.variation).map(a => [a.id, a])); const combinations = new Set<string>();
      const validateMap = (map: Record<string, string>, field: string) => { for (const [key, value] of Object.entries(map)) { const a = attrs.get(key); if (!a || (value !== "" && !a.options.includes(value))) v.fail(`${field}.${key}`, "Must reference a variation attribute and one of its options."); } };
      validateMap(result.defaultAttributes, "defaultAttributes");
      result.variations.forEach((row, i) => { validateMap(row.attributes, `variations[${i}].attributes`); if (!attrs.size) v.fail(`variations[${i}]`, "Add at least one variation attribute."); for (const key of attrs.keys()) if (!(key in row.attributes)) v.fail(`variations[${i}].attributes`, "Include each variation attribute (empty means any option)."); const combination = JSON.stringify([...attrs.keys()].sort().map(k => [k, row.attributes[k] || ""])); if (combinations.has(combination)) v.fail(`variations[${i}].attributes`, "Duplicate attribute combination."); combinations.add(combination); });
      if (new Set(result.variations.map(row => row.id)).size !== result.variations.length) v.fail("variations", "Variation IDs must be unique.");
    }
  }
  v.finish(); return result;
}
export function normalizeSampleTerm(input: unknown, existing?: SampleTerm): SampleTerm { const v = new Validator(), r = object(input), name = v.name(r.name, "name"), taxonomy = v.text(r.taxonomy, "taxonomy", "", 32); if (!["category", "post_tag", "product_cat", "product_tag", "product_brand", "product_shipping_class"].includes(taxonomy) && !/^pa_[a-z][a-z0-9_-]{0,27}$/.test(taxonomy)) v.fail("taxonomy", "Unsupported taxonomy."); if (existing && existing.taxonomy !== taxonomy) v.fail("taxonomy", "An existing term cannot change taxonomy."); const result: SampleTerm = { id: existing?.id || v.identifier(r.id, "id", id("term")), name, taxonomy: taxonomy as SampleTaxonomy, slug: v.slug(r.slug, "slug", name), description: v.text(r.description, "description"), parentId: v.optionalId(r.parentId, "parentId"), imageId: v.optionalId(r.imageId, "imageId") }; if (result.parentId && !["category", "product_cat", "product_brand"].includes(taxonomy)) v.fail("parentId", "This taxonomy is not hierarchical."); if (result.imageId && !["product_cat", "product_brand"].includes(taxonomy)) v.fail("imageId", "Images are only supported for product categories and brands."); v.finish(); return result; }
export function normalizeSampleGlobalAttribute(input: unknown, existing?: SampleGlobalAttribute): SampleGlobalAttribute { const v = new Validator(), r = object(input), name = v.name(r.name, "name"), slug = v.slug(r.slug, "slug", name, true); const result: SampleGlobalAttribute = { id: existing?.id || v.identifier(r.id, "id", id("global")), name, slug, type: v.choice(r.type, "type", ["select"], "select"), orderBy: v.choice(r.orderBy, "orderBy", ["menu_order", "name", "name_num", "id"], "menu_order"), hasArchives: v.bool(r.hasArchives, "hasArchives") }; if (existing && slug !== existing.slug) v.fail("slug", "Global attribute slugs are immutable because terms reference their taxonomy."); const reserved = new Set(["attachment", "author", "category", "cat", "tag", "taxonomy", "type", "name", "p", "page", "paged", "post", "post_type", "product", "order", "orderby", "s", "search", "year", "monthnum", "day", "feed", "fields", "error"]); if (reserved.has(slug)) v.fail("slug", "Reserved WordPress query name."); v.finish(); return result; }
export function sampleProductDependencies(row: SampleContent): string[] { return row.kind === "product" ? [...row.upsellIds, ...row.crossSellIds, ...(row.productType === "grouped" ? row.childrenIds : [])] : []; }
function assetRefs(row: SampleContent): string[] { const html = [row.content, row.kind === "post" ? row.excerpt : row.shortDescription]; const out = [row.featuredImageId || "", ...html.flatMap(text => [...text.matchAll(/\{\{sample-asset:([a-z0-9-]+)\}\}/g)].map(m => m[1]))]; if (row.kind === "product") { out.push(...row.galleryIds); if (row.productType === "simple") out.push(...row.downloads.map(d => d.assetId)); if (row.productType === "variable") for (const variation of row.variations) out.push(variation.imageId || "", ...variation.downloads.map(d => d.assetId)); } return out.filter(Boolean); }
export function validateSampleLibrary(library: SampleContentLibrary): void {
  const v = new Validator(), terms = new Map(library.terms.map(t => [t.id, t])), attributes = new Map(library.attributes.map(a => [a.id, a])), assets = new Map(library.assets.map(a => [a.id, a])), content = new Map(library.content.map(c => [c.id, c]));
  for (const [name, rows] of [["content", library.content], ["terms", library.terms], ["attributes", library.attributes], ["assets", library.assets]] as const) if (new Set(rows.map(r => r.id)).size !== rows.length) v.fail(name, "Duplicate IDs.");
  const unique = (values: Array<[string, string]>, field: string) => { const seen = new Map<string, string>(); for (const [value, owner] of values) if (value) { if (seen.has(value)) v.fail(field, `${value} is used by both ${seen.get(value)} and ${owner}.`); seen.set(value, owner); } };
  unique(library.content.map(c => [`${c.kind}:${c.slug}`, c.id]), "slug"); unique(library.terms.map(t => [`${t.taxonomy}:${t.slug}`, t.id]), "term.slug"); unique(library.attributes.map(a => [a.slug, a.id]), "attribute.slug");
  const identifiers: Array<[string, string]> = [], globalIds: Array<[string, string]> = [];
  const checkImage = (assetId: string | undefined, field: string) => { if (assetId && assets.get(assetId)?.kind !== "image") v.fail(field, `Image ${assetId} is missing or not an image.`); };
  const checkTerm = (termId: string, taxonomy: string, field: string) => { if (terms.get(termId)?.taxonomy !== taxonomy) v.fail(field, `Term ${termId} must exist in ${taxonomy}.`); };
  for (const term of library.terms) { if (term.parentId) checkTerm(term.parentId, term.taxonomy, `${term.id}.parentId`); checkImage(term.imageId, `${term.id}.imageId`); if (term.taxonomy.startsWith("pa_") && !library.attributes.some(a => `pa_${a.slug}` === term.taxonomy)) v.fail(term.id, "Missing global attribute definition."); const visited = new Set([term.id]); let parent = term.parentId; while (parent && terms.has(parent)) { if (visited.has(parent)) { v.fail(term.id, "Term hierarchy contains a cycle."); break; } visited.add(parent); parent = terms.get(parent)?.parentId; } }
  for (const row of library.content) {
    row.categoryIds.forEach(t => checkTerm(t, row.kind === "post" ? "category" : "product_cat", `${row.id}.categoryIds`)); row.tagIds.forEach(t => checkTerm(t, row.kind === "post" ? "post_tag" : "product_tag", `${row.id}.tagIds`)); checkImage(row.featuredImageId, `${row.id}.featuredImageId`);
    for (const a of assetRefs(row)) if (!assets.has(a)) v.fail(row.id, `Missing asset ${a}.`);
    for (const html of [row.content, row.kind === "post" ? row.excerpt : row.shortDescription]) for (const match of html.matchAll(/\{\{sample-asset:([a-z0-9-]+)\}\}/g)) checkImage(match[1], `${row.id}.content`);
    if (row.kind !== "product") continue;
    row.brandIds.forEach(t => checkTerm(t, "product_brand", `${row.id}.brandIds`)); row.galleryIds.forEach(a => checkImage(a, `${row.id}.galleryIds`));
    const checkInventory = (inventory: SampleInventory, owner: string) => { identifiers.push([inventory.sku.toLowerCase(), owner]); globalIds.push([inventory.globalUniqueId, owner]); };
    checkInventory(row.inventory, row.id); if (row.shipping.classId) checkTerm(row.shipping.classId, "product_shipping_class", `${row.id}.shipping.classId`);
    for (const linked of sampleProductDependencies(row)) if (linked === row.id || content.get(linked)?.kind !== "product") v.fail(row.id, `Linked product ${linked} must exist and cannot be itself.`);
    for (const a of row.attributes) if (a.globalId) { const global = attributes.get(a.globalId); if (!global) v.fail(`${row.id}.attributes`, `Missing global attribute ${a.globalId}.`); else for (const option of a.options) checkTerm(option, `pa_${global.slug}`, `${row.id}.attributes`); }
    const checkDownloads = (downloads: SampleDownload[], field: string) => { for (const d of downloads) if (!assets.has(d.assetId)) v.fail(field, `Missing download asset ${d.assetId}.`); };
    if (row.productType === "simple") checkDownloads(row.downloads, `${row.id}.downloads`);
    if (row.productType === "variable") for (const variation of row.variations) { checkInventory(variation.inventory, variation.id); checkImage(variation.imageId, `${variation.id}.imageId`); if (variation.shipping.classId) checkTerm(variation.shipping.classId, "product_shipping_class", `${variation.id}.shipping.classId`); checkDownloads(variation.downloads, `${variation.id}.downloads`); }
  }
  unique(identifiers, "inventory.sku"); unique(globalIds, "inventory.globalUniqueId");
  const visitGroup = (root: string, visited: Set<string>) => { const row = content.get(root); if (row?.kind !== "product" || row.productType !== "grouped") return; if (visited.has(root)) { v.fail(root, "Grouped-product hierarchy contains a cycle."); return; } const next = new Set(visited).add(root); for (const child of row.childrenIds) visitGroup(child, next); };
  library.content.filter(c => c.kind === "product" && c.productType === "grouped").forEach(c => visitGroup(c.id, new Set())); v.finish();
}
const locks = new Map<string, Promise<unknown>>();
export class SampleContentRegistry {
  readonly root: string; readonly registryFile: string;
  constructor(root: string) { this.root = path.resolve(root); this.registryFile = path.join(this.root, "sample-content.json"); }
  async list(): Promise<SampleContentLibrary> { if (!(await exists(this.registryFile))) return emptyLibrary(); const raw = JSON.parse(await readFile(this.registryFile, "utf8")); if (raw?.schemaVersion !== 1 || ![raw.content, raw.terms, raw.attributes, raw.assets].every(Array.isArray)) throw new BuilderError("invalid_sample_registry", "Unsupported sample-content registry."); return raw; }
  private async mutate<T>(operation: (library: SampleContentLibrary) => Promise<T> | T): Promise<T> { const previous = locks.get(this.root) || Promise.resolve(); const pending = previous.catch(() => {}).then(async () => { const library = await this.list(); const result = await operation(library); validateSampleLibrary(library); await writeJson(this.registryFile, library); return result; }); locks.set(this.root, pending); try { return await pending; } finally { if (locks.get(this.root) === pending) locks.delete(this.root); } }
  async get(contentId: string): Promise<SampleContent> { const row = (await this.list()).content.find(c => c.id === contentId); if (!row) throw new BuilderError("sample_not_found", `Sample ${contentId} was not found.`); return row; }
  async save(input: unknown, contentId?: string): Promise<SampleContent> { return this.mutate(library => { const existing = contentId ? library.content.find(c => c.id === contentId) : undefined; if (contentId && !existing) throw new BuilderError("sample_not_found", "Sample was not found."); const result = normalizeSampleContent(input, existing); if (!existing && library.content.some(c => c.id === result.id)) throw new BuilderError("resource_exists", "Sample ID already exists."); if (existing) library.content[library.content.indexOf(existing)] = result; else library.content.push(result); return result; }); }
  async saveTerm(input: unknown, termId?: string): Promise<SampleTerm> { return this.mutate(library => { const existing = termId ? library.terms.find(t => t.id === termId) : undefined; if (termId && !existing) throw new BuilderError("sample_not_found", "Term was not found."); const result = normalizeSampleTerm(input, existing); if (existing) library.terms[library.terms.indexOf(existing)] = result; else library.terms.push(result); return result; }); }
  async saveAttribute(input: unknown, attributeId?: string): Promise<SampleGlobalAttribute> { return this.mutate(library => { const existing = attributeId ? library.attributes.find(a => a.id === attributeId) : undefined; if (attributeId && !existing) throw new BuilderError("sample_not_found", "Attribute was not found."); const result = normalizeSampleGlobalAttribute(input, existing); if (existing) library.attributes[library.attributes.indexOf(existing)] = result; else library.attributes.push(result); return result; }); }
  async duplicate(contentId: string): Promise<SampleContent> { const original = await this.get(contentId); const library = await this.list(); const copy: any = structuredClone(original); delete copy.id; copy.title += " (copy)"; let suffix = 2; copy.slug = `${original.slug}-copy`; while (library.content.some(c => c.kind === copy.kind && c.slug === copy.slug)) copy.slug = `${original.slug}-copy-${suffix++}`; if (copy.kind === "product") { copy.inventory.sku = ""; copy.inventory.globalUniqueId = ""; for (const variation of copy.variations || []) { variation.id = id("variation"); variation.inventory.sku = ""; variation.inventory.globalUniqueId = ""; } } copy.status = "draft"; return this.save(copy); }
  async remove(resource: "content" | "terms" | "attributes" | "assets", resourceId: string): Promise<void> { await this.mutate(async library => { const rows = library[resource] as Array<{ id: string }>; const found = rows.findIndex(r => r.id === resourceId); if (found < 0) throw new BuilderError("sample_not_found", "Resource was not found."); if (resource === "content") { const dir = path.join(this.root, "profiles"); if (await exists(dir)) for (const entry of await readdir(dir)) if (entry.endsWith(".json")) { const profile = JSON.parse(await readFile(path.join(dir, entry), "utf8")); if (Array.isArray(profile.sampleContentIds) && profile.sampleContentIds.includes(resourceId)) throw new BuilderError("resource_in_use", `Sample is selected by profile ${profile.name || entry}.`); } } rows.splice(found, 1); try { validateSampleLibrary(library); } catch (error) { if (error instanceof SampleContentValidationError) throw new BuilderError("resource_in_use", `Resource is still referenced: ${error.message}`); throw error; } }); }
  async importAsset(source: string, options: { kind: "image" | "download"; filename?: string; alt?: string; caption?: string; description?: string }): Promise<SampleAsset> {
    const info = await stat(source); const maximum = options.kind === "image" ? MAX_IMAGE : MAX_DOWNLOAD; if (!info.isFile() || info.size === 0 || info.size > maximum) throw new BuilderError("invalid_sample_asset", `File must be nonempty and at most ${maximum / 1024 ** 2} MiB.`);
    const bytes = await readFile(source); const filename = path.basename(options.filename || source); const ext = path.extname(filename).toLowerCase(); let mime = "", extension = "";
    if (bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])) && ext === ".png") { mime = "image/png"; extension = ".png"; }
    else if (bytes[0] === 255 && bytes[1] === 216 && bytes[2] === 255 && [".jpg", ".jpeg"].includes(ext)) { mime = "image/jpeg"; extension = ".jpg"; }
    else if (["GIF87a", "GIF89a"].includes(bytes.subarray(0, 6).toString("ascii")) && ext === ".gif") { mime = "image/gif"; extension = ".gif"; }
    else if (bytes.subarray(0, 4).toString("ascii") === "RIFF" && bytes.subarray(8, 12).toString("ascii") === "WEBP" && ext === ".webp") { mime = "image/webp"; extension = ".webp"; }
    else if (options.kind === "download" && bytes.subarray(0, 5).toString("ascii") === "%PDF-" && ext === ".pdf") { mime = "application/pdf"; extension = ".pdf"; }
    else if (options.kind === "download" && ext === ".txt" && !bytes.includes(0) && Buffer.from(bytes.toString("utf8")).equals(bytes)) { mime = "text/plain"; extension = ".txt"; }
    if (!mime) throw new BuilderError("invalid_sample_asset", "Unsupported file type or file signature. Use JPEG, PNG, GIF, WebP, or PDF/plain text downloads.");
    const assetId = id("asset"), relative = `sample-assets/${assetId}${extension}`, target = path.join(this.root, relative); await ensureDir(path.dirname(target)); await copyFile(source, target);
    const v = new Validator(); const result: SampleAsset = { id: assetId, filename, file: relative, mime, size: info.size, sha256: await sha256File(target), kind: options.kind, alt: v.text(options.alt, "alt", "", 2000), caption: v.text(options.caption, "caption", "", 10000), description: v.text(options.description, "description", "", 10000) };
    try { v.finish(); return await this.mutate(library => { library.assets.push(result); return result; }); } catch (error) { await rm(target, { force: true }); throw error; }
  }
  async saveAsset(assetId: string, input: unknown): Promise<SampleAsset> { return this.mutate(library => { const row = library.assets.find(a => a.id === assetId); if (!row) throw new BuilderError("sample_not_found", "Asset was not found."); const v = new Validator(), r = object(input); row.alt = v.text(r.alt, "alt", row.alt, 2000); row.caption = v.text(r.caption, "caption", row.caption, 10000); row.description = v.text(r.description, "description", row.description, 10000); v.finish(); return row; }); }
  async resolveAsset(assetId: string): Promise<SampleAsset & { absoluteFile: string }> { const row = (await this.list()).assets.find(a => a.id === assetId); if (!row) throw new BuilderError("sample_not_found", `Asset ${assetId} was not found.`); if (!/^sample-assets\/asset-[a-z0-9-]+\.(?:png|jpg|gif|webp|pdf|txt)$/.test(row.file)) throw new BuilderError("invalid_sample_asset", "Unsafe stored asset path."); const base = await realpath(path.join(this.root, "sample-assets")), absoluteFile = await realpath(path.join(this.root, row.file)); if (!absoluteFile.startsWith(base + path.sep)) throw new BuilderError("invalid_sample_asset", "Asset escapes the library."); if ((await stat(absoluteFile)).size !== row.size || await sha256File(absoluteFile) !== row.sha256) throw new BuilderError("sample_asset_checksum_mismatch", `Asset ${row.filename} failed integrity verification.`); return { ...row, absoluteFile }; }
  async resolve(ids: string[]): Promise<ResolvedSampleContent> {
    const v = new Validator(); const selectedIds = v.ids(ids, "sampleContentIds"); v.finish(); const library = await this.list(); validateSampleLibrary(library); const content = new Map(library.content.map(c => [c.id, c])); const selected = new Map<string, SampleContent>(); const queue = [...selectedIds]; for (let i = 0; i < queue.length; i++) { if (selected.has(queue[i])) continue; const row = content.get(queue[i]); if (!row) throw new BuilderError("sample_not_found", `Selected sample ${queue[i]} was not found.`); selected.set(row.id, row); queue.push(...sampleProductDependencies(row)); }
    const termIds = new Set<string>(), attributeIds = new Set<string>(), assetIds = new Set<string>();
    for (const row of selected.values()) { row.categoryIds.forEach(i => termIds.add(i)); row.tagIds.forEach(i => termIds.add(i)); assetRefs(row).forEach(i => assetIds.add(i)); if (row.kind === "product") { row.brandIds.forEach(i => termIds.add(i)); if (row.shipping.classId) termIds.add(row.shipping.classId); for (const a of row.attributes) if (a.globalId) { attributeIds.add(a.globalId); a.options.forEach(i => termIds.add(i)); } if (row.productType === "variable") for (const variant of row.variations) if (variant.shipping.classId) termIds.add(variant.shipping.classId); } }
    for (const termId of termIds) { const term = library.terms.find(t => t.id === termId)!; if (term.parentId) termIds.add(term.parentId); if (term.imageId) assetIds.add(term.imageId); }
    const assets = await Promise.all([...assetIds].map(i => this.resolveAsset(i))); if (assets.reduce((sum, a) => sum + a.size, 0) > SAMPLE_BUILD_ASSET_LIMIT) throw new BuilderError("sample_asset_limit", "Selected sample assets exceed 500 MiB.");
    return { schemaVersion: 1, selectedIds, content: [...selected.values()], terms: library.terms.filter(t => termIds.has(t.id)), attributes: library.attributes.filter(a => attributeIds.has(a.id)), assets };
  }
}
