<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

return array(
    'wordpress_options' => array(
        'default_comment_status',
        'default_ping_status',
        'users_can_register',
        'show_on_front',
        'timezone_string',
        'date_format',
        'time_format',
        'start_of_week',
        'thumbnail_size_w',
        'thumbnail_size_h',
        'medium_size_w',
        'medium_size_h',
        'large_size_w',
        'large_size_h',
    ),

    'elementor_options' => array(
        'elementor_css_print_method',
        'elementor_disable_color_schemes',
        'elementor_disable_typography_schemes',
        'elementor_unfiltered_files_upload',
        'elementor_beta',
        'elementor_enable_inspector',
        'elementor_font_display',
        'elementor_landing_pages_activation',
        'elementor_experiment-container',
        'elementor_experiment-e_swiper_latest',
        'elementor_experiment-e_optimized_markup',
        'elementor_experiment-additional_custom_breakpoints',
    ),

    'woocommerce_options' => array(
        'woocommerce_allowed_countries',
        'woocommerce_all_except_countries',
        'woocommerce_specific_allowed_countries',
        'woocommerce_calc_taxes',
        'woocommerce_cart_redirect_after_add',
        'woocommerce_checkout_address_2_field',
        'woocommerce_checkout_company_field',
        'woocommerce_checkout_highlight_required_fields',
        'woocommerce_checkout_phone_field',
        'woocommerce_currency',
        'woocommerce_currency_pos',
        'woocommerce_default_customer_address',
        'woocommerce_dimension_unit',
        'woocommerce_downloads_add_hash_to_filename',
        'woocommerce_downloads_count_partial',
        'woocommerce_downloads_deliver_inline',
        'woocommerce_downloads_grant_access_after_payment',
        'woocommerce_downloads_redirect_fallback_allowed',
        'woocommerce_downloads_require_login',
        'woocommerce_enable_ajax_add_to_cart',
        'woocommerce_enable_checkout_login_reminder',
        'woocommerce_enable_coupons',
        'woocommerce_enable_delayed_account_creation',
        'woocommerce_enable_guest_checkout',
        'woocommerce_enable_myaccount_registration',
        'woocommerce_enable_review_rating',
        'woocommerce_enable_reviews',
        'woocommerce_enable_shipping_calc',
        'woocommerce_enable_signup_and_login_from_checkout',
        'woocommerce_file_download_method',
        'woocommerce_hide_out_of_stock_items',
        'woocommerce_hold_stock_minutes',
        'woocommerce_manage_stock',
        'woocommerce_notify_low_stock',
        'woocommerce_notify_low_stock_amount',
        'woocommerce_notify_no_stock',
        'woocommerce_notify_no_stock_amount',
        'woocommerce_price_decimal_sep',
        'woocommerce_price_display_suffix',
        'woocommerce_price_num_decimals',
        'woocommerce_price_thousand_sep',
        'woocommerce_prices_include_tax',
        'woocommerce_registration_generate_password',
        'woocommerce_registration_generate_username',
        'woocommerce_review_rating_required',
        'woocommerce_review_rating_verification_label',
        'woocommerce_review_rating_verification_required',
        'woocommerce_ship_to_countries',
        'woocommerce_ship_to_destination',
        'woocommerce_shipping_cost_requires_address',
        'woocommerce_shipping_hide_rates_when_free',
        'woocommerce_shipping_tax_class',
        'woocommerce_single_image_width',
        'woocommerce_tax_based_on',
        'woocommerce_tax_classes',
        'woocommerce_tax_display_cart',
        'woocommerce_tax_display_shop',
        'woocommerce_tax_round_at_subtotal',
        'woocommerce_tax_total_display',
        'woocommerce_thumbnail_image_width',
        'woocommerce_weight_unit',
    ),

    'persian_woocommerce_options' => array(
        'persian_woocommerce_translates',
    ),
);
